### ISSUE TITLE
大佬 能提供一个冰冻效果吗

### ISSUE THREAD

**Issue by stripluagio** [ifengzp/cocos-awesome#2]
大佬 能提供一个冰冻效果吗
shader 还没入门。暂时无能为力。

**Comment by ifengzp** [comment]
我不知道你要哪种冰冻效果，如果只是简单的颜色滤镜的话，你可以查看我已经实现了的滤镜demo的例子，里面有一个蓝色的滤镜，[https://github.com/ifengzp/cocos-awesome/blob/master/doc/Filter/%E5%B8%B8%E8%A7%81%E6%BB%A4%E9%95%9C.md](url)
